[package]
name = "vizia_style"
description = "The style components of vizia"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cssparser = "0.34"
cssparser-color = "0.2"
skia-safe = { version = "0.80", features = ["gl", "textlayout", "svg"] }
selectors = "0.26"
morphorm = "0.6.5"
smallvec = "1.0"
bitflags = "2.6"
precomputed-hash = "*"

[target."cfg(target_os = \"linux\")".dependencies.skia-safe]
version = "0.80"
features = ["gl", "textlayout", "svg", "x11", "wayland"]

[lints]
workspace = true
