[package]
name = "vizia_winit"
description = "Winit backend for vizia"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
x11 = ["winit/x11", "glutin/x11", "glutin-winit/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen", "winit/wayland-csd-adwaita", "glutin-winit/wayland", "copypasta?/wayland"]
clipboard = ["copypasta"]
accesskit = ["accesskit_winit"]

[dependencies]
vizia_input.workspace = true
vizia_core.workspace = true
vizia_id.workspace = true
vizia_window.workspace = true

accesskit = "0.16"
winit = { version = "0.30" }
skia-safe = {version = "0.75", features = ["gl"]}
glutin = { version = "0.32" }
copypasta = {version = "0.10", optional = true, default-features = false }
accesskit_winit = { version = "0.22", optional = true }
glutin-winit = { version = "0.5" }
gl-rs = { package = "gl", version = "0.14.0" }
hashbrown = "0.14"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59", default-features = false, features = [ "Win32_Graphics_Dwm" ] }

[lints]
workspace = true
