[package]
name = "vizia_winit"
version = "0.1.0"
authors = ["George Atkinson"]
edition = "2021"
license = "MIT"
repository = "https://github.com/vizia/vizia"
description = "Winit backend for vizia"
rust-version = "1.60"

[features]
x11 = ["winit/x11", "glutin?/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen", "winit/wayland-csd-adwaita", "glutin?/wayland", "glutin?/wayland-dlopen", "copypasta?/wayland"]
clipboard = ["copypasta"]

[dependencies]
vizia_input = { path = "../vizia_input" }
vizia_core = { path = "../vizia_core" }
vizia_id = { path = "../vizia_id" }
vizia_window = { path = "../vizia_window" }

winit = { version = "0.27.2", default-features = false }
femtovg = { git = "https://github.com/femtovg/femtovg", rev = "018883b4a22805992f90e373e85020e9732bd11e", default-features = false }
glutin = { version = "0.29.1", default-features = false, optional = true }
copypasta = {version = "0.8.1", optional = true, default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.29.1", default-features = false }
femtovg = { git = "https://github.com/femtovg/femtovg", rev = "018883b4a22805992f90e373e85020e9732bd11e", features = ["glutin"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web_sys = { version = "0.3", package = "web-sys", features=["console", "WebGlContextAttributes"] }
console_error_panic_hook = "0.1.5"
