[package]
name = "vizia_winit"
version = "0.1.0"
authors = ["George Atkinson"]
edition = "2021"
license = "MIT"
repository = "https://github.com/vizia/vizia"
description = "Winit backend for vizia"
rust-version = "1.60"

[features]
x11 = ["winit/x11", "glutin?/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen", "winit/wayland-csd-adwaita", "copypasta?/wayland"]
clipboard = ["copypasta"]

[dependencies]
vizia_input = { path = "../vizia_input" }
vizia_core = { path = "../vizia_core" }
vizia_id = { path = "../vizia_id" }
vizia_window = { path = "../vizia_window" }

winit = { version = "0.28.1", default-features = false }
femtovg = "0.6.0"
# femtovg = { git = "https://github.com/rhelmot/femtovg", rev = "09f4837fff4d2cd58ddc4674d0d7e1296a4123aa", default-features = false }
#femtovg = { path = "../../../femtovg", default-features = false }
glutin = { version = "0.30.3", default-features = false, optional = true }
copypasta = {version = "0.8.1", optional = true, default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.30.3", default-features = false }
femtovg = "0.6.0"
# femtovg = { git = "https://github.com/rhelmot/femtovg", rev = "09f4837fff4d2cd58ddc4674d0d7e1296a4123aa", features = ["glutin"] }
#femtovg = { path = "../../../femtovg", default-features = false, features = ["glutin"] }
glutin-winit = "0.3.0"
raw-window-handle = "0.5.0"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web_sys = { version = "0.3", package = "web-sys", features=["console", "WebGlContextAttributes"] }
console_error_panic_hook = "0.1.5"
