[package]
name = "vizia_winit"
version = "0.1.0"
authors = ["George Atkinson"]
edition = "2021"
license = "MIT"
repository = "https://github.com/vizia/vizia"
description = "Winit backend for vizia"
rust-version = "1.65"

[features]
x11 = ["winit/x11", "glutin/x11", "glutin-winit/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen", "winit/wayland-csd-adwaita", "glutin-winit/wayland", "copypasta?/wayland"]
clipboard = ["copypasta"]
accesskit = ["accesskit_winit"]

[dependencies]
vizia_input = { path = "../vizia_input" }
vizia_core = { path = "../vizia_core" }
vizia_id = { path = "../vizia_id" }
vizia_window = { path = "../vizia_window" }

accesskit = "0.12"
winit = { version = "0.29", default-features = false }
femtovg = "0.9"
glutin = { version = "0.31", default-features = false }
copypasta = {version = "0.10", optional = true, default-features = false }
accesskit_winit = { version = "0.18", optional = true }
glutin-winit = { version = "0.4", default-features = false, features = ["egl", "glx", "wgl"] }
raw-window-handle = "0.5"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", default-features = false, features = ["minwindef", "dwmapi"] }
