[package]
name = "vizia_window"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The window components of vizia"
rust-version = "1.60"

[dependencies]
vizia_input = { path = "../vizia_input" }
vizia_style = { path = "../vizia_style" }
# morphorm = {path = "../../../morphorm" }
morphorm = {git = "https://github.com/vizia/morphorm", rev = "b7afddf587b139061fcb18898c2f0fba36570d33" }
accesskit = "0.11.0"
#morphorm = { path = "../../../morphorm", features = ["rounding"] }
