[package]
name = "vizia_window"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The window components of vizia"
rust-version = "1.60"

[dependencies]
vizia_input = { path = "../vizia_input" }
#morphorm = { git = "https://github.com/vizia/morphorm", features = ["rounding"], rev = "c14e888b1d66719fc3f13ccdb1ea01a10368ef9e" }
morphorm = { path = "../../../morphorm", features = ["rounding"] }
