[package]
name = "vizia_storage"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The storage data structures of vizia"
rust-version = "1.65"

[dependencies]
vizia_id = { path = "../vizia_id" }

# morphorm = {path = "../../../morphorm" }
morphorm = {git = "https://github.com/vizia/morphorm.git", branch = "auto-min-size2"}
# morphorm = "0.6.4"

[lints]
workspace = true
