[package]
name = "vizia_core"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "Core components of vizia"
rust-version = "1.76"

[features]
clipboard = ["copypasta"]
x11 = ["copypasta?/x11"]
wayland = ["copypasta?/wayland"]

[dependencies]
vizia_derive = { path = "../vizia_derive" }
vizia_storage = { path = "../vizia_storage" }
vizia_id = { path = "../vizia_id" }
vizia_input = { path = "../vizia_input" }
vizia_window = { path = "../vizia_window" }
vizia_style = { path = "../vizia_style"}
accesskit = "0.12.0"

skia-safe = { version = "0.75", features = ["textlayout", "svg"] }
# morphorm = {path = "../../../morphorm" }
morphorm = {git = "https://github.com/vizia/morphorm.git", branch = "auto-min-size2"}
# morphorm = "0.6.4"
bitflags = "2.6"
fnv = "1.0"
fluent-bundle = "0.15"
fluent-langneg = "0.13"
unic-langid = {version = "0.9.4", features = ["macros"]}
sys-locale = "0.3.1"
unicode-segmentation = "1.11.0"
copypasta = {version = "0.10.1", optional = true, default-features = false }
chrono = "0.4"
hashbrown = "0.14"
log = "0.4"
indexmap = "2.4"
qfilter = "0.2"
# reqwest = { version = "0.11.9", features = ["blocking"] }
web-time = "1.1"
comrak = {version = "0.27", default-features = false }
open = "5.2"
sha2 = "0.10"

[lib]
doctest = false

[lints]
workspace = true
