[package]
name = "vizia_core"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "Core components of vizia"
rust-version = "1.65"

[features]
clipboard = ["copypasta"]
x11 = ["copypasta?/x11"]
wayland = ["copypasta?/wayland"]
embedded_fonts = []

[dependencies]
vizia_derive = { path = "../vizia_derive" }
vizia_storage = { path = "../vizia_storage" }
vizia_id = { path = "../vizia_id" }
vizia_input = { path = "../vizia_input" }
vizia_window = { path = "../vizia_window" }
vizia_style = { path = "../vizia_style"}
accesskit = "0.12.0"

skia-safe = { version = "0.75", features = ["textlayout"] }
# morphorm = {path = "../../../morphorm" }
morphorm = {git = "https://github.com/vizia/morphorm.git", branch = "auto-min-size2"}
# morphorm = "0.6.4"
bitflags = "2.4.2"
fnv = "1.0.7"
fluent-bundle = "0.15.2"
fluent-langneg = "0.13.0"
unic-langid = {version = "0.9.4", features = ["macros"]}
sys-locale = "0.3.1"
unicode-segmentation = "1.11.0"
copypasta = {version = "0.10.1", optional = true, default-features = false }
chrono = "0.4.34"
hashbrown = "0.14.3"
log = "0.4.20"
indexmap = "2.2.3"
qfilter = "0.1.6"
# reqwest = { version = "0.11.9", features = ["blocking"] }
web-time = "1.1.0"
comrak = "0.24"
open = "5.2"

[lib]
doctest = false

[lints]
workspace = true
