[package]
name = "vizia_id"
description = "Generational ID type used by vizia"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
