name: Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs at 15:00 UTC on Fri
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - run: rustup update
      - run: cargo audit --version
      # RUSTSEC-2020-0097: xcb - Soundness issue with base::Error
      # RUSTSEC-2021-0019: xcb - Multiple soundness issues
      # RUSTSEC-2021-0119: nix - Out-of-bounds write in nix::unistd::getgrouplist - waiting for new winit release
      # RUSTSEC-2020-0159: chrono - Dev Dependency
      # RUSTSEC-2020-0071: time - Dev Dependency
      # RUSTSEC-2022-0048: xml-rs is Unmaintained
      - run: cargo audit --deny warnings --ignore RUSTSEC-2020-0097 --ignore RUSTSEC-2021-0019 --ignore RUSTSEC-2021-0119 --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2022-0048